import { organizerRates, suggestedOrganizerRate, organizerTotals } from '../../../shared/lincolnOrganizerContract';

const money = (value) => new Intl.NumberFormat('es-BO', { style: 'currency', currency: 'BOB' }).format(Number(value || 0));
export default function OrganizerProposal({ draft, rooms, onChange }) {
  const days = draft.organizerDays || [];
  const updateDay = (id, patch) => onChange(current => {
    const organizerDays = current.organizerDays.map(day => {
      if (day.id !== id) return day;
      const next = { ...day, ...patch };
      if (patch.guestCount != null && !day.customPrice) next.amountBs = suggestedOrganizerRate(next.guestCount) || 0;
      return next;
    });
    const first = organizerDays[0];
    return { ...current, organizerDays, eventDate: first?.date || '', roomId: first?.roomId || '', roomName: first?.roomName || '', guestCount: Number(first?.guestCount || 0) };
  });
  const updateExtra = (id, patch) => onChange(current => ({ ...current, extras: current.extras.map(line => line.id === id ? { ...line, ...patch } : line) }));
  const totals = organizerTotals(draft);
  return <section className="lincoln-contract-flow-section lincoln-organizer-proposal">
    <div className="lincoln-contract-flow-title"><small>PASO 2 · ALQUILER PARA ORGANIZADORES</small><h3>Salón, jornadas y extras</h3><p>Tarifa fija por salón y cantidad de asistentes. Los precios de referencia pueden ajustarse para este contrato.</p></div>
    <div className="lincoln-organizer-rate-list">{organizerRates.map(rate => <div key={rate.capacity}><span>Hasta {rate.capacity} personas</span><strong>{money(rate.amountBs)}</strong></div>)}</div>
    <div className="lincoln-organizer-section-title"><h4>Jornadas de alquiler</h4><button type="button" onClick={() => onChange(current => ({ ...current, organizerDays: [...current.organizerDays, { id: crypto.randomUUID(), date: '', roomId: current.roomId, roomName: current.roomName, guestCount: 150, amountBs: 7000 }] }))}>+ Agregar jornada</button></div>
    {days.map((day, index) => <article className="lincoln-organizer-day" key={day.id}><header><strong>Jornada {index + 1}</strong><button type="button" disabled={days.length === 1} onClick={() => onChange(current => { const organizerDays = current.organizerDays.filter(row => row.id !== day.id); const first = organizerDays[0]; return { ...current, organizerDays, eventDate: first.date, roomId: first.roomId, roomName: first.roomName, guestCount:Number(first.guestCount || 0), extras: current.extras.map(line => line.dayId === day.id ? { ...line, dayId: '' } : line) }; })}>Eliminar jornada</button></header>
      <div className="lincoln-organizer-fields"><label>Fecha<input aria-label={`Fecha jornada ${index + 1}`} type="date" value={day.date} onChange={e => updateDay(day.id, { date: e.target.value })} /></label><label>Salón<select aria-label={`Salón jornada ${index + 1}`} value={day.roomId || ''} onChange={e => { const room = rooms.find(row => row.id === e.target.value); updateDay(day.id, { roomId: e.target.value, roomName: room?.name || '' }); }}><option value="">Seleccionar salón</option>{rooms.map(room => <option key={room.id} value={room.id}>{room.name}</option>)}</select></label>
        <label>Asistentes<input aria-label={`Asistentes jornada ${index + 1}`} type="number" min="1" value={day.guestCount} onChange={e => updateDay(day.id, { guestCount: Number(e.target.value) })} /></label><label>Precio fijo del salón (Bs)<input aria-label={`Precio salón jornada ${index + 1}`} type="number" min="0" step="0.01" value={day.amountBs} onChange={e => updateDay(day.id, { amountBs: Number(e.target.value), customPrice: true })} /></label>
      </div><footer><span>{day.customPrice ? 'Precio acordado para este contrato' : suggestedOrganizerRate(day.guestCount) == null ? 'Más de 300 asistentes: indica el precio acordado.' : 'Tarifa sugerida según asistentes'}</span><button type="button" disabled={suggestedOrganizerRate(day.guestCount) == null} onClick={() => updateDay(day.id, { amountBs: suggestedOrganizerRate(day.guestCount), customPrice: false })}>Usar tarifa sugerida</button></footer>
    </article>)}
    <div className="lincoln-organizer-section-title"><div><h4>Productos y servicios adicionales</h4><p>Registra alquileres, ventas o servicios con cantidad y precio unitario acordado.</p></div><button type="button" onClick={() => onChange(current => ({ ...current, extras: [...current.extras, { id: crypto.randomUUID(), description: '', kind: 'rental', quantity: 1, unitCostBs: 0, costMode: 'per_event', selected: true, dayId: '' }] }))}>+ Agregar extra</button></div>
    {!draft.extras.length ? <p className="lincoln-organizer-hint">Sin extras. El contrato incluye únicamente el alquiler del salón.</p> : draft.extras.map((line, index) => <article className="lincoln-organizer-day" key={line.id}><header><strong>Extra {index + 1} · {money(Number(line.quantity || 0) * Number(line.unitCostBs || 0))}</strong><button type="button" onClick={() => onChange(current => ({ ...current, extras: current.extras.filter(row => row.id !== line.id) }))}>Eliminar extra</button></header><div className="lincoln-organizer-fields"><label>Tipo<select aria-label={`Tipo extra ${index + 1}`} value={line.kind || 'service'} onChange={e => updateExtra(line.id, { kind: e.target.value })}><option value="rental">Alquiler de producto</option><option value="sale">Venta de producto</option><option value="service">Servicio adicional</option></select></label><label>Descripción<input aria-label={`Descripción extra ${index + 1}`} value={line.description} maxLength="500" onChange={e => updateExtra(line.id, { description: e.target.value })} /></label><label>Cantidad<input aria-label={`Cantidad extra ${index + 1}`} type="number" min="0.01" step="0.01" value={line.quantity} onChange={e => updateExtra(line.id, { quantity: Number(e.target.value) })} /></label><label>Precio unitario (Bs)<input aria-label={`Precio extra ${index + 1}`} type="number" min="0" step="0.01" value={line.unitCostBs} onChange={e => updateExtra(line.id, { unitCostBs: Number(e.target.value) })} /></label><label>Aplicar a<select value={line.dayId || ''} onChange={e => updateExtra(line.id, { dayId: e.target.value })}><option value="">Todo el evento</option>{days.map((day, dayIndex) => <option key={day.id} value={day.id}>Jornada {dayIndex + 1} · {day.date || 'Fecha pendiente'}</option>)}</select></label></div></article>)}
    <div className="lincoln-organizer-rate-list"><div><span>Alquiler del salón</span><strong>{money(totals.baseBs)}</strong></div><div><span>Productos y servicios extras</span><strong>{money(totals.extrasBs)}</strong></div><div><span>Total antes de descuentos</span><strong>{money(totals.grossBs)}</strong></div><div><span>Anticipo de referencia (50%)</span><strong>{money(totals.totalBs / 2)}</strong></div></div>
    <p className="lincoln-organizer-hint">Garantía de referencia: Bs 500, separada del total. Saldo: 7 días antes del evento. SOBODAYCOM a cargo del organizador; alquiler de mobiliario con EL COPETÍN.</p>
  </section>;
}
