const number = (value) => {
  const parsed = Number(value ?? 0);
  return Number.isFinite(parsed) ? parsed : 0;
};

const normalize = (value) => String(value ?? '')
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .toLowerCase()
  .trim();

/**
 * Reconciles repeated snapshots generated by partial returns. For the same
 * processing stage only the latest snapshot is valid; different stages keep
 * their accumulated damaged quantity while only the last stage keeps missing
 * units, because earlier missing units are provisional until return closes.
 */
export const consolidateReturnIssueLines = (rows, scopeKey = '') => {
  const source = Array.isArray(rows) ? rows : [];
  const groups = new Map();

  source.forEach((line, index) => {
    if (
      number(line?.damagedQty) <= 0
      && number(line?.missingQty) <= 0
      && number(line?.penaltyBs) <= 0
    ) return;
    const lineKey = String(line?.lineKey ?? '').trim();
    const itemId = String(line?.itemId ?? '').trim();
    const itemName = String(line?.itemName ?? line?.name ?? 'Item').trim() || 'Item';
    const rowScope = String(
      scopeKey
      || line?.rentalId
      || line?.contractId
      || line?.orderCode
      || line?.contractCode
      || '',
    ).trim();
    const identity = lineKey
      || String(line?.id ?? '').trim()
      || (itemId ? `item:${itemId}` : `name:${normalize(itemName)}`);
    const groupKey = `${rowScope}|${identity}`;
    const previousProcessedQty = Math.max(0, number(line?.previousProcessedQty));
    const createdAtMs = new Date(
      line?.partialRegisteredAt
      ?? line?.registeredAt
      ?? line?.updatedAt
      ?? line?.createdAt
      ?? 0,
    ).getTime();

    if (!groups.has(groupKey)) {
      groups.set(groupKey, {
        lineKey,
        itemId,
        itemName,
        stages: new Map(),
      });
    }

    const group = groups.get(groupKey);
    const stageKey = String(previousProcessedQty);
    const existing = group.stages.get(stageKey);
    const candidate = {
      line,
      index,
      previousProcessedQty,
      createdAtMs: Number.isFinite(createdAtMs) ? createdAtMs : 0,
    };
    if (
      !existing
      || candidate.createdAtMs > existing.createdAtMs
      || (candidate.createdAtMs === existing.createdAtMs && candidate.index > existing.index)
    ) {
      group.stages.set(stageKey, candidate);
    }
  });

  return Array.from(groups.values()).map((group) => {
    const stages = Array.from(group.stages.values())
      .sort((left, right) => (
        left.previousProcessedQty - right.previousProcessedQty
        || left.createdAtMs - right.createdAtMs
        || left.index - right.index
      ));
    const lastStage = stages.at(-1);
    const lastLine = lastStage?.line ?? {};
    const damagedQty = stages.reduce(
      (sum, stage) => sum + Math.max(0, number(stage.line?.damagedQty)),
      0,
    );
    const missingQty = Math.max(0, number(lastLine?.missingQty));

    const findLastPositive = (field) => {
      for (let index = stages.length - 1; index >= 0; index -= 1) {
        const value = Math.max(0, number(stages[index].line?.[field]));
        if (value > 0) return value;
      }
      return 0;
    };
    const findLastText = (...fields) => {
      for (let index = stages.length - 1; index >= 0; index -= 1) {
        for (const field of fields) {
          const value = String(stages[index].line?.[field] ?? '').trim();
          if (value) return value;
        }
      }
      return '';
    };

    const damagedUnitChargeBs = findLastPositive('damagedUnitChargeBs');
    const missingUnitChargeBs = findLastPositive('missingUnitChargeBs');
    const computedPenaltyBs = Number((
      damagedQty * damagedUnitChargeBs
      + missingQty * missingUnitChargeBs
    ).toFixed(2));
    const fallbackPenaltyBs = stages.reduce(
      (max, stage) => Math.max(max, Math.max(0, number(stage.line?.penaltyBs))),
      0,
    );

    return {
      ...lastLine,
      lineKey: group.lineKey || String(lastLine?.lineKey ?? '').trim(),
      itemId: group.itemId || String(lastLine?.itemId ?? '').trim(),
      itemName: group.itemName,
      damagedQty,
      missingQty,
      damagedUnitChargeBs,
      missingUnitChargeBs,
      damagedFeeBs: Number((damagedQty * damagedUnitChargeBs).toFixed(2)),
      missingFeeBs: Number((missingQty * missingUnitChargeBs).toFixed(2)),
      penaltyBs: computedPenaltyBs > 0 ? computedPenaltyBs : fallbackPenaltyBs,
      damageNote: findLastText('damageNote', 'note'),
      chargeOwner: findLastText('chargeOwner') || 'cliente',
    };
  });
};
