import { formatLincolnBs, formatLincolnDate } from '../shared/lincolnFormatters';
import LincolnSettlementSummary from './LincolnSettlementSummary';
import LincolnSettlementExpenses from './LincolnSettlementExpenses';

const paymentLabel = (type) => ({ advance: 'ANTICIPO', installment: 'A CUENTA', balance: 'SALDO', replacement: 'REPOSICIÓN' }[type] ?? String(type || 'INGRESO').toUpperCase());

export default function LincolnSettlementDetail({ detail, saving, onBack, onNewExpense, onToggleStatus }) {
  const { event, summary, payments = [], expenses = [] } = detail;
  const closed = summary?.settlementStatus === 'closed';
  return <div className="lincoln-phase3-view"><section className="lincoln-phase3-detail-head"><div><button type="button" className="lincoln-phase3-back" onClick={onBack}>← Rendiciones</button><small>Rendición de evento</small><h2>{event?.code} · {event?.clientName || event?.eventType}</h2><p>{formatLincolnDate(event?.eventDate)} · {event?.eventType || 'Evento'} · {event?.roomName || 'Sin salón'}</p></div><button type="button" className={closed ? 'lincoln-phase3-secondary' : 'lincoln-phase3-primary'} disabled={saving} onClick={() => onToggleStatus(closed ? 'open' : 'closed')}>{closed ? 'Reabrir rendición' : 'Cerrar rendición'}</button></section><LincolnSettlementSummary summary={summary}/><section className="lincoln-phase3-card"><header className="lincoln-phase3-card-head"><div><small>Ingresos del evento</small><h3>Pagos y reposiciones aplicados</h3></div><strong className="lincoln-phase3-total">{formatLincolnBs(summary?.operatingIncomeBs)}</strong></header><div className="lincoln-phase3-table-wrap"><table className="lincoln-phase3-table is-compact"><thead><tr><th>Fecha</th><th>Movimiento</th><th>Concepto</th><th>Destino</th><th>Respaldo</th><th>Monto</th></tr></thead><tbody>{payments.length ? payments.map((row) => <tr key={row.id}><td>{formatLincolnDate(row.date)}</td><td>{row.code || '—'}</td><td><span className="lincoln-phase3-category is-income">{paymentLabel(row.type)}</span></td><td>{row.destination || '—'}</td><td>{row.reference || row.receiptCode || '—'}</td><td className="is-money"><strong>{formatLincolnBs(row.amountBs)}</strong></td></tr>) : <tr><td colSpan="6" className="lincoln-phase3-empty-cell">Todavía no existen ingresos operativos para este evento.</td></tr>}</tbody></table></div></section><LincolnSettlementExpenses expenses={expenses} onNewExpense={onNewExpense}/><section className="lincoln-phase3-closing"><div><span>Total ingresos</span><strong>{formatLincolnBs(summary?.operatingIncomeBs)}</strong></div><div><span>Total gastos</span><strong>{formatLincolnBs(summary?.operatingExpenseBs)}</strong></div><div className={Number(summary?.utilityBs) < 0 ? 'is-negative' : 'is-result'}><span>Utilidad / saldo</span><strong>{formatLincolnBs(summary?.utilityBs)}</strong></div><small>Garantías separadas: cobradas {formatLincolnBs(summary?.guaranteeCollectedBs)} · devueltas {formatLincolnBs(summary?.guaranteeReturnedBs)} · retenidas {formatLincolnBs(summary?.guaranteeHeldBs)}</small></section></div>;
}
